/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../../app/app.component';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from '../../../transfer-state';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {animation: ([] as any[])}
}
);
export function View_AppComponent_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Universal Web Application']),
    import0.ɵtextDef((null as any),['\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        '/'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.AppComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import0.ɵnodeValue(view,5).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵdirectiveDef(10,(null as any),0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import3.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import0.ɵtextDef((null as any),['Home']),
    import0.ɵtextDef((null as any),['\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),2,'a',[[
        'routerLink',
<<<<<<< HEAD
        '/about'
=======
        '/lazy'
>>>>>>> dc4570b... 211th Commit
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.AppComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import0.ɵnodeValue(view,9).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵdirectiveDef(10,(null as any),0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import3.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
<<<<<<< HEAD
    import0.ɵtextDef((null as any),['About']),
=======
    import0.ɵtextDef((null as any),['Lazy']),
>>>>>>> dc4570b... 211th Commit
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵelementDef(256,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵdirectiveDef(2,(null as any),0,import2.RouterOutlet,[
      import2.RouterOutletMap,
      import0.ViewContainerRef,
      import0.ComponentFactoryResolver,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:import1.AppComponent = view.component;
    const currVal_0:any = '/';
    check(view,5,0,currVal_0);
<<<<<<< HEAD
    const currVal_1:any = '/about';
=======
    const currVal_1:any = '/lazy';
>>>>>>> dc4570b... 211th Commit
    check(view,9,0,currVal_1);
  },(check,view) => {
    var comp:import1.AppComponent = view.component;
    const currVal_0:any = import0.ɵnodeValue(view,5).target;
    const currVal_1:any = import0.ɵnodeValue(view,5).href;
    check(view,4,0,currVal_0,currVal_1);
    const currVal_2:any = import0.ɵnodeValue(view,9).target;
    const currVal_3:any = import0.ɵnodeValue(view,9).href;
    check(view,8,0,currVal_2,currVal_3);
  });
}
const RenderType_AppComponent_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_AppComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent),
    import0.ɵdirectiveDef(1025,(null as any),0,import1.AppComponent,[import4.TransferState],(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import1.AppComponent> = import0.ɵcreateComponentFactory('app-root',import1.AppComponent,View_AppComponent_Host_0);