/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../../app/app.module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/router';
import * as import4 from '@angular/common';
<<<<<<< HEAD
=======
import * as import5 from './home-view.component.ngfactory';
import * as import6 from '../../../app/home-view.component';
>>>>>>> dc4570b... 211th Commit
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _HttpModule_0:import2.HttpModule;
  _ɵa_1:any;
  _RouterModule_2:import3.RouterModule;
  _AppModule_3:import1.AppModule;
  __BrowserXhr_4:import2.BrowserXhr;
  __ResponseOptions_5:import2.BaseResponseOptions;
  __XSRFStrategy_6:any;
  __XHRBackend_7:import2.XHRBackend;
  __RequestOptions_8:import2.BaseRequestOptions;
  __Http_9:any;
  __APP_BASE_HREF_10:any;
  __ROUTER_CONFIGURATION_11:any;
  __LocationStrategy_12:any;
  __Location_13:import4.Location;
  __UrlSerializer_14:import3.DefaultUrlSerializer;
  __RouterOutletMap_15:import3.RouterOutletMap;
  __NgModuleFactoryLoader_16:import0.SystemJsNgModuleLoader;
  __ROUTES_17:any[];
  __Router_18:any;
  __ActivatedRoute_19:any;
  _NoPreloading_20:import3.NoPreloading;
  _PreloadingStrategy_21:any;
  _RouterPreloader_22:import3.RouterPreloader;
  __PreloadAllModules_23:import3.PreloadAllModules;
  __NgProbeToken_24:any[];
  __ROUTER_INITIALIZER_25:any;
  __APP_BOOTSTRAP_LISTENER_26:any[];
  constructor(parent:import0.Injector) {
<<<<<<< HEAD
    super(parent,[
      HomeComponentNgFactory,
      AboutComponentNgFactory
    ]
    ,([] as any[]));
=======
    super(parent,[import5.HomeViewNgFactory],([] as any[]));
>>>>>>> dc4570b... 211th Commit
  }
  get _BrowserXhr_4():import2.BrowserXhr {
    if ((this.__BrowserXhr_4 == null)) { (this.__BrowserXhr_4 = new import2.BrowserXhr()); }
    return this.__BrowserXhr_4;
  }
  get _ResponseOptions_5():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_5 == null)) { (this.__ResponseOptions_5 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_5;
  }
  get _XSRFStrategy_6():any {
    if ((this.__XSRFStrategy_6 == null)) { (this.__XSRFStrategy_6 = import2.ɵb()); }
    return this.__XSRFStrategy_6;
  }
  get _XHRBackend_7():import2.XHRBackend {
    if ((this.__XHRBackend_7 == null)) { (this.__XHRBackend_7 = new import2.XHRBackend(this._BrowserXhr_4,this._ResponseOptions_5,this._XSRFStrategy_6)); }
    return this.__XHRBackend_7;
  }
  get _RequestOptions_8():import2.BaseRequestOptions {
    if ((this.__RequestOptions_8 == null)) { (this.__RequestOptions_8 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_8;
  }
  get _Http_9():any {
    if ((this.__Http_9 == null)) { (this.__Http_9 = import2.ɵc(this._XHRBackend_7,this._RequestOptions_8)); }
    return this.__Http_9;
  }
  get _APP_BASE_HREF_10():any {
    if ((this.__APP_BASE_HREF_10 == null)) { (this.__APP_BASE_HREF_10 = '/'); }
    return this.__APP_BASE_HREF_10;
  }
  get _ROUTER_CONFIGURATION_11():any {
    if ((this.__ROUTER_CONFIGURATION_11 == null)) { (this.__ROUTER_CONFIGURATION_11 = {}); }
    return this.__ROUTER_CONFIGURATION_11;
  }
  get _LocationStrategy_12():any {
    if ((this.__LocationStrategy_12 == null)) { (this.__LocationStrategy_12 = import3.ɵc(this.parent.get(import4.PlatformLocation),this._APP_BASE_HREF_10,this._ROUTER_CONFIGURATION_11)); }
    return this.__LocationStrategy_12;
  }
  get _Location_13():import4.Location {
    if ((this.__Location_13 == null)) { (this.__Location_13 = new import4.Location(this._LocationStrategy_12)); }
    return this.__Location_13;
  }
  get _UrlSerializer_14():import3.DefaultUrlSerializer {
    if ((this.__UrlSerializer_14 == null)) { (this.__UrlSerializer_14 = new import3.DefaultUrlSerializer()); }
    return this.__UrlSerializer_14;
  }
  get _RouterOutletMap_15():import3.RouterOutletMap {
    if ((this.__RouterOutletMap_15 == null)) { (this.__RouterOutletMap_15 = new import3.RouterOutletMap()); }
    return this.__RouterOutletMap_15;
  }
  get _NgModuleFactoryLoader_16():import0.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_16 == null)) { (this.__NgModuleFactoryLoader_16 = new import0.SystemJsNgModuleLoader(this.parent.get(import0.Compiler),this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_16;
  }
  get _ROUTES_17():any[] {
      if ((this.__ROUTES_17 == null)) { (this.__ROUTES_17 = [[
        {
          path: '',
<<<<<<< HEAD
          component: import1.HomeComponent,
=======
          component: import6.HomeView,
>>>>>>> dc4570b... 211th Commit
          pathMatch: 'full'
        }
        ,
        {
<<<<<<< HEAD
          path: 'about',
          component: import1.AboutComponent,
          pathMatch: 'full'
=======
          path: 'lazy',
          loadChildren: './lazy.module#LazyModule'
>>>>>>> dc4570b... 211th Commit
        }

      ]
    ]); }
    return this.__ROUTES_17;
  }
  get _Router_18():any {
    if ((this.__Router_18 == null)) { (this.__Router_18 = import3.ɵe(this.parent.get(import0.ApplicationRef),this._UrlSerializer_14,this._RouterOutletMap_15,this._Location_13,this,this._NgModuleFactoryLoader_16,this.parent.get(import0.Compiler),this._ROUTES_17,this._ROUTER_CONFIGURATION_11,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)))); }
    return this.__Router_18;
  }
  get _ActivatedRoute_19():any {
    if ((this.__ActivatedRoute_19 == null)) { (this.__ActivatedRoute_19 = import3.ɵf(this._Router_18)); }
    return this.__ActivatedRoute_19;
  }
  get _PreloadAllModules_23():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_23 == null)) { (this.__PreloadAllModules_23 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_23;
  }
  get _NgProbeToken_24():any[] {
    if ((this.__NgProbeToken_24 == null)) { (this.__NgProbeToken_24 = [import3.ɵb()]); }
    return this.__NgProbeToken_24;
  }
  get _ROUTER_INITIALIZER_25():any {
    if ((this.__ROUTER_INITIALIZER_25 == null)) { (this.__ROUTER_INITIALIZER_25 = import3.ɵg(this._Router_18,this.parent.get(import0.ApplicationRef),this._RouterPreloader_22,this._ROUTER_CONFIGURATION_11)); }
    return this.__ROUTER_INITIALIZER_25;
  }
  get _APP_BOOTSTRAP_LISTENER_26():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_26 == null)) { (this.__APP_BOOTSTRAP_LISTENER_26 = [this._ROUTER_INITIALIZER_25]); }
    return this.__APP_BOOTSTRAP_LISTENER_26;
  }
  createInternal():import1.AppModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._ɵa_1 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._RouterModule_2 = new import3.RouterModule(this._ɵa_1);
    this._AppModule_3 = new import1.AppModule();
    this._NoPreloading_20 = new import3.NoPreloading();
    this._PreloadingStrategy_21 = this._NoPreloading_20;
    this._RouterPreloader_22 = new import3.RouterPreloader(this._Router_18,this._NgModuleFactoryLoader_16,this.parent.get(import0.Compiler),this,this._PreloadingStrategy_21);
    return this._AppModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.ɵa)) { return this._ɵa_1; }
    if ((token === import3.RouterModule)) { return this._RouterModule_2; }
    if ((token === import1.AppModule)) { return this._AppModule_3; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_4; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_5; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_6; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_7; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_8; }
    if ((token === import2.Http)) { return this._Http_9; }
    if ((token === import4.APP_BASE_HREF)) { return this._APP_BASE_HREF_10; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_11; }
    if ((token === import4.LocationStrategy)) { return this._LocationStrategy_12; }
    if ((token === import4.Location)) { return this._Location_13; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_14; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_15; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_16; }
    if ((token === import3.ROUTES)) { return this._ROUTES_17; }
    if ((token === import3.Router)) { return this._Router_18; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_19; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_20; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_21; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_22; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_23; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_24; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_25; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_26; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._RouterPreloader_22.ngOnDestroy();
  }
}
<<<<<<< HEAD
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_HomeComponent,
  data: {animation: ([] as any[])}
}
);
export function View_HomeComponent_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['home works!']),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(null as any),(null as any));
}
const RenderType_HomeComponent_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_HomeComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent),
    import0.ɵdirectiveDef(1024,(null as any),0,import1.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import0.ComponentFactory<import1.HomeComponent> = import0.ɵcreateComponentFactory('ng-component',import1.HomeComponent,View_HomeComponent_Host_0);
const styles_AboutComponent:any[] = ([] as any[]);
export const RenderType_AboutComponent:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_AboutComponent,
  data: {animation: ([] as any[])}
}
);
export function View_AboutComponent_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['about works!']),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(null as any),(null as any));
}
const RenderType_AboutComponent_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_AboutComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent),
    import0.ɵdirectiveDef(1024,(null as any),0,import1.AboutComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AboutComponentNgFactory:import0.ComponentFactory<import1.AboutComponent> = import0.ɵcreateComponentFactory('ng-component',import1.AboutComponent,View_AboutComponent_Host_0);
=======
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
>>>>>>> dc4570b... 211th Commit
