/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../../app/home-view.component';
const styles_HomeView:any[] = ([] as any[]);
export const RenderType_HomeView:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_HomeView,
  data: {animation: ([] as any[])}
}
);
export function View_HomeView_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['app works!']),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(null as any),(null as any));
}
const RenderType_HomeView_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_HomeView_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'home-view',([] as any[]),(null as any),(null as any),(null as any),View_HomeView_0,RenderType_HomeView),
    import0.ɵdirectiveDef(1024,(null as any),0,import1.HomeView,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeViewNgFactory:import0.ComponentFactory<import1.HomeView> = import0.ɵcreateComponentFactory('home-view',import1.HomeView,View_HomeView_Host_0);